`timescale 1ns / 1ps

module tb_ntt_top;
    reg clk, rst, start, load_we;
    reg [7:0] load_addr, rd_addr;
    reg [11:0] load_data;
    wire done;
    wire [11:0] rd_data;

    
    ntt_top dut (
    .clk       (clk),
    .rst       (rst),
    .start     (start),
    .done      (done),
    .busy      (busy),
    .load_we   (load_we),
    .load_addr (load_addr),
    .load_data (load_data),
    .rd_addr   (rd_addr),
    .rd_data   (rd_data)
);// Connect all signals

    always #5 clk = ~clk;

    integer i, fd, status;

    initial begin

    $dumpfile("sim_output/ntt_waveform.vcd"); // Name of the file
        $dumpvars(0, tb_ntt_top);                // Dump all signals in the testbench and below
        clk = 0; rst = 1; start = 0; load_we = 0;
        #100 rst = 0; 
        
        // 1. Read input generated by Python
        fd = $fopen("sim_output/input.txt", "r");
        for (i = 0; i < 256; i = i + 1) begin
            status = $fscanf(fd, "%d", load_data);
            load_addr = i[7:0];
            load_we = 1;
            @(posedge clk); #1;
        end
        load_we = 0;

        // 2. Run NTT
        #20 start = 1; #10 start = 0;
        wait(done);
        #100;

        // 3. Write results to file for Python to grade
        fd = $fopen("sim_output/ntt_out.txt", "w");
        for (i = 0; i < 256; i = i + 1) begin
            rd_addr = i[7:0];   // Drive address
            @(posedge clk); #1; // Wait for RAM to latch address
            @(posedge clk); #1; // Wait for RAM to output data (latency)
            $fdisplay(fd, "%d", rd_data);
        end
        $fclose(fd);
        $finish;
    end
endmodule